const ImageCharactersDatas = [
    {'name': 'AileBlanche.Line.webp'},
    {'name': 'bouton-d-or.png'},
    {'name': 'caramel2.png'},
    {'name': 'EtoileDuSapin.webp'},
    {'name': 'Etoiledefeu.png'},
    {'name': 'ficelle.png'},
    {'name': 'Jolie_Plume2.png'},
    {'name': 'Museaucendre.png'},
    {'name': 'Plume_Grise.png'},
    {'name': 'pomme-de-pinwarrior.png'},
    {'name': 'Princesse.png'},
    {'name': 'Rhume_des_Foins.png'},
    {'name': 'riviere_d_argent.png'},
    {'name': 'Shadowstar.png'},
    {'name': 'Shadowstar.png'},
    {'name': 'AiledeColombe-Line-Guerrière.png'},
    {'name': 'Alderheart1.webp'},
    {'name': 'Aurore_Violette_Guerrière.png'},
    {'name': 'Bluestar-warrior.png'},
    {'name': 'Conteur-des-Pointes-Rocheuses.png'},
    {'name': 'corbeau-grive.png'},
    {'name': 'Croc-jaune.png'},
    {'name': 'etoile_de_Jais.png'},
]
export default ImageCharactersDatas